### ISSUE TITLE
ValueError: Schedule step must be greater or equal than 1 round

### ISSUE THREAD

**Issue by beardo01** [knjcode/mxnet-finetuner#10]
Hey there,

Running `sudo -E docker-compose run finetuner` with the default config.yml and some images in sub folders of `train`, `test` and `valid`. Each time the image run I get an error stating:

> ValueError: Schedule step must be greater or equal than 1 round

From what I can tell, that indicates that the learning parameter is getting too low, however I can't seem to track down the source. I have tried this across two different computers and am getting the same error on both (could it be my images as they were the same across both?).

Any feedback is appreciated.

**Comment by knjcode** [comment]
Sorry for late reply.

I do not know what is the cause.
Could you try to work with the latest version of the pre-built docker image?

Feel free to re-open this issue if needed.
